name: Build Native Installers

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    name: Build for ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21 with JavaFX
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'liberica' # Includes JavaFX

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build Fat JAR
        run: mvn clean package

      - name: Extract app version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set up jpackage path (macOS only)
        if: runner.os == 'macOS'
        run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Create native installer (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir dist
          jpackage \
            --input target \
            --main-jar gsm-1.0-SNAPSHOT.jar \
            --main-class com.pach.gsm.Launcher \
            --name GSM \
            --type ${{ runner.os == 'macOS' && 'dmg' || 'deb' }} \
            --dest dist \
            --app-version "${{ steps.version.outputs.VERSION }}" \
            --icon resources/icon/${{ runner.os == 'macOS' && 'icon.icns' || 'icon.png' }}
        shell: bash

      - name: Create native installer (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          jpackage ^
          --input target ^
          --main-jar gsm-1.0-SNAPSHOT.jar ^
          --main-class com.pach.gsm.Launcher ^
          --name GSM ^
          --type exe ^
          --dest dist ^
          --app-version ${{ steps.version.outputs.VERSION }} ^
          --vendor Pachuchi ^
          --win-dir-chooser ^
          --win-menu ^
          --win-shortcut ^
          --icon resources/icon/icon.ico
                

      - name: Upload installers to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}